### PR TITLE
Remove unwanted type property

### PR DESCRIPTION
**Pull request by lzap**
It looks like it creates an unwanted type property which is reported as a warning in my IDE and the official Swagger editor as `Sibling properties to $ref are ignored.`

https://github.com/foresterorg/forester/commit/ae8997e2028d90825c91ade47dc885cc56e45310

However, unfortunately it is causing the Python client API generator to miss an import so it generates unusable code:

https://github.com/foresterorg/forester-client-python/commit/38870b8d5825500b802d0664a23fe638b290d71e

This patch fixes it.

### CODE REVIEW

**Comment by lzap** [comment]
Tests do fail, however, I don’t think it makes sense to run them against `main`, it should compile the source code and run them against the PR, what do you think?

**Comment by lzap** [comment]
Tests do fail, not sure how am I supposed to handle this. I guess I need to regenerate with the latest stable version.

**Review by VojtechVitek — APPROVED** [review]
LGTM

The indentation looks slightly off but I guess we can fix that later. Looks like the YAML works.

**Comment by VojtechVitek** [comment]
Indentation fixed in https://github.com/webrpc/gen-openapi/pull/13.

Thanks for the fix, @lzap !

Released as `-target=openapi@v0.11.3`

**Comment by lzap** [comment]
Oh damn, how did I miss this. Thanks!

**Pull request merged**
